server:
  port: 8706 # 服务提供方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/,http://${eureka.instance.hostname}:8001/eureka/,http://${eureka.instance.hostname}:8002/eureka/
  instance:
    hostname: localhost

#当前服务名称
spring:
  application:
    name:  depository
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopDep?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
ribbon:
  ReadTimeout=60000
  ConnectTimeout=60000
  MaxAutoRetries=0
  MaxAutoRetriesNextServer=1