---
spring:
 application:
  name: spring-cloud-eureka
 profiles: peer1
server:
 port: 8000
eureka:
 instance:
  hostname: peer1
 client:
  serviceUrl:
   defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/
  fetch-registry: false
  register-with-eureka: false
 server:
  #注意：更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置。
  eviction-interval-timer-in-ms: 4000  # 清理间隔(单位毫秒，默认是60*1000)
  #关闭注册中心的保护机制, 默认false, 不推荐关闭
  #eureka.server.enable-self-preservation: false
---
spring:
 application:
  name: spring-cloud-eureka
 profiles: peer2
server:
 port: 8001
eureka:
 instance:
  hostname: peer2
 client:
  serviceUrl:
   defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/
  fetch-registry: false
  register-with-eureka: false
---
spring:
 application:
  name: spring-cloud-eureka
 profiles: peer3
server:
 port: 8002
eureka:
 instance:
  hostname: peer3
  #Eureka client 默认 30秒会向 Server 端发送一次心跳;
  #Server端 默认是90秒对没有接收到 client 端的续租请求会认为client挂机
  #lease-renewal-interval-in-seconds: 10
 client:
  serviceUrl:
   defaultZone: http://peer2:8001/eureka/,http://peer1:8000/eureka/
  fetch-registry: false
  register-with-eureka: false

